# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180116_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='media',
            field=models.ManyToManyField(blank=True, to='cms.Media'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='media',
            field=models.ManyToManyField(blank=True, to='cms.Media'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='playlist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Playlist'),
        ),
    ]
