# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180116_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
